# Generated by Django 5.2.16 on 2026-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=120)),
                ('telegram_bot_token_configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'notification settings',
            },
        ),
    ]
