# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'email'), ('telegram', 'telegram'), ('max', 'MAX'), ('admin', 'admin')], max_length=20)),
                ('template_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=20)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('recipient_hint', models.CharField(blank=True, max_length=160)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=160)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_e1aed1_idx'), models.Index(fields=['object_type', 'object_id'], name='notificatio_object__9d1741_idx')],
            },
        ),
    ]
