# Generated by Django 6.1 on 2026-08-28 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_part_marking_category_part_marking_required_and_more'),
        ('orders', '0003_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Не в сборке'), ('reserved', 'В сборке'), ('packed', 'Упакован'), ('dispatched', 'Передан в доставку')], db_index=True, default='new', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Номер у поставщика')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Ожидаем поставку'), ('partial', 'Принято частично'), ('received', 'Принято полностью'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=20)),
                ('note', models.TextField(blank=True, max_length=2000, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitting', 'Проверить регистрацию'), ('accepted', 'Регистрация обрабатывается'), ('ready', 'Зарегистрирован в СДЭК'), ('transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён в СДЭК'), ('error', 'Требует внимания')], db_index=True, default='draft', max_length=20)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('tariff_code', models.PositiveIntegerField(default=136, verbose_name='Код тарифа СДЭК')),
                ('recipient_name', models.CharField(max_length=160, verbose_name='ФИО получателя')),
                ('recipient_phone', models.CharField(max_length=30, verbose_name='Телефон получателя')),
                ('city_code', models.PositiveIntegerField(verbose_name='Код города СДЭК')),
                ('city_label', models.CharField(max_length=160, verbose_name='Город (для менеджера)')),
                ('delivery_point', models.CharField(blank=True, max_length=30, verbose_name='Код ПВЗ СДЭК')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Адрес для доставки до двери')),
                ('weight_g', models.PositiveIntegerField(verbose_name='Вес посылки с упаковкой, г')),
                ('length_cm', models.PositiveIntegerField(verbose_name='Длина, см')),
                ('width_cm', models.PositiveIntegerField(verbose_name='Ширина, см')),
                ('height_cm', models.PositiveIntegerField(verbose_name='Высота, см')),
                ('cdek_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('cdek_number', models.CharField(blank=True, max_length=40)),
                ('provider_status', models.CharField(blank=True, max_length=80)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_days', models.CharField(blank=True, max_length=60)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('label_uuid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='Ячейка хранения')),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('minimum', models.PositiveIntegerField(default=0, verbose_name='Минимальный остаток')),
                ('unit_weight_g', models.PositiveIntegerField(default=0, verbose_name='Вес одной детали, г')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stock', to='catalog.part')),
            ],
            options={
                'permissions': [('manage_inventory', 'Can adjust physical warehouse inventory'), ('process_purchases', 'Can place and receive purchase orders'), ('process_fulfillment', 'Can reserve, pack and dispatch customer orders'), ('manage_shipments', 'Can prepare and submit CDEK shipments')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.fulfillment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adjustment', 'Корректировка'), ('receipt', 'Приёмка'), ('reserve', 'Резерв'), ('release', 'Снятие резерва'), ('dispatch', 'Отгрузка')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_delta', models.IntegerField(default=0)),
                ('balance_after', models.PositiveIntegerField()),
                ('reserved_after', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.purchaseorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.stockitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=160)),
                ('target', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Заказано')),
                ('received', models.PositiveIntegerField(default=0)),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена закупки, ₽')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.purchaseorder')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='warehouse_purchase_positive_qty'), models.CheckConstraint(condition=models.Q(('received__lte', models.F('quantity'))), name='warehouse_receipt_within_order'), models.CheckConstraint(condition=models.Q(('unit_cost_rub__gte', 0)), name='warehouse_purchase_nonnegative_cost'), models.UniqueConstraint(fields=('purchase', 'part'), name='warehouse_unique_purchase_part')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='warehouse_reserved_within_stock'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('fulfillment', 'stock'), name='warehouse_unique_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='warehouse_reservation_positive_qty'),
        ),
    ]
