# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_retention_days', models.PositiveIntegerField(default=1095)),
                ('cancelled_order_retention_days', models.PositiveIntegerField(default=1095)),
                ('notification_retention_days', models.PositiveIntegerField(default=365)),
                ('audit_retention_days', models.PositiveIntegerField(default=1095)),
                ('anonymize_test_data_after_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'retention policy',
                'verbose_name_plural': 'retention policy',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy_policy', 'Политика персональных данных'), ('privacy_consent', 'Согласие на обработку ПДн'), ('terms', 'Условия заказа'), ('delivery', 'Доставка'), ('payment', 'Оплата'), ('warranty', 'Гарантия'), ('returns', 'Возврат')], max_length=40)),
                ('version', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-published_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='unique_legal_document_version')],
            },
        ),
    ]
