# Generated by Django 5.2.16 on 2026-08-15 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_part_legacy_id_alter_part_condition_and_more'),
        ('leads', '0002_customerrequest_consent_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed_by_manager', 'confirmed by manager'), ('payment_pending', 'payment pending'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('fulfilled', 'fulfilled'), ('refunded', 'refunded'), ('partially_refunded', 'partially refunded')], default='draft', max_length=40)),
                ('customer_name', models.CharField(max_length=160)),
                ('contact', models.CharField(max_length=160)),
                ('vehicle', models.CharField(blank=True, max_length=240)),
                ('manager_note', models.TextField(blank=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('total_amount_rub', models.PositiveIntegerField(default=0)),
                ('delivery_terms', models.CharField(blank=True, max_length=240)),
                ('warranty_terms', models.CharField(blank=True, max_length=240)),
                ('vat_label', models.CharField(default='НДС не задан', max_length=80)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='leads.customerrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=240)),
                ('article', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_rub', models.PositiveIntegerField(default=0)),
                ('line_total_rub', models.PositiveIntegerField(default=0)),
                ('condition_snapshot', models.CharField(blank=True, max_length=120)),
                ('delivery_snapshot', models.CharField(blank=True, max_length=160)),
                ('warranty_snapshot', models.CharField(blank=True, max_length=160)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.part')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed_by_manager', 'confirmed by manager'), ('payment_pending', 'payment pending'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('fulfilled', 'fulfilled'), ('refunded', 'refunded'), ('partially_refunded', 'partially refunded')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['token'], name='orders_orde_token_190540_idx'),
        ),
    ]
