# Generated by Django 5.2.16 on 2026-08-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_fiscal_name_orderitem_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_order_pii', 'Can view personal data in orders')]},
        ),
    ]
