# Generated by Django 5.2.16 on 2026-08-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_fiscal_name_orderitem_payment_method_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('sale', 'sale'), ('refund', 'refund')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('validated', 'validated'), ('sent', 'sent'), ('failed', 'failed')], default='draft', max_length=40)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('amount_rub', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('fiscal_number', models.CharField(blank=True, max_length=120)),
                ('fiscal_document', models.CharField(blank=True, max_length=120)),
                ('fiscal_sign', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipts', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipts', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceiptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fiscal.fiscalreceipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('article', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_rub', models.PositiveIntegerField(default=0)),
                ('line_total_rub', models.PositiveIntegerField(default=0)),
                ('vat_label', models.CharField(default='НДС не задан', max_length=80)),
                ('payment_subject', models.CharField(default='commodity', max_length=80)),
                ('payment_method', models.CharField(default='full_payment', max_length=80)),
                ('unit', models.CharField(default='шт.', max_length=40)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.fiscalreceipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['payment', 'receipt_type'], name='fiscal_fisc_payment_4ff6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['status', 'created_at'], name='fiscal_fisc_status_e40e5b_idx'),
        ),
    ]
