# Generated by Django 5.2.16 on 2026-08-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        ('orders', '0002_orderitem_fiscal_name_orderitem_payment_method_and_more'),
        ('payments', '0002_alter_payment_options_payment_provider_order_number_and_more'),
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_receipts', to='refunds.refund'),
        ),
        migrations.AddConstraint(
            model_name='fiscalreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_type', 'sale')), fields=('payment', 'receipt_type'), name='unique_sale_receipt_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='fiscalreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_type', 'refund')), fields=('refund', 'receipt_type'), name='unique_refund_receipt_per_refund'),
        ),
    ]
