# Generated by Django 5.2.16 on 2026-08-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(default='demo', max_length=80)),
                ('contact_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('years', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.carmodel')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('model_name', models.CharField(blank=True, max_length=160)),
                ('condition', models.CharField(choices=[('new', 'new'), ('contract', 'contract'), ('restored', 'restored')], default='new', max_length=40)),
                ('quality', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('primary_oem', models.CharField(blank=True, max_length=120)),
                ('primary_article', models.CharField(blank=True, max_length=120)),
                ('search_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.manufacturer')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility', to='catalog.part')),
            ],
            options={
                'verbose_name_plural': 'part compatibility',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('oem', 'OEM'), ('article', 'article'), ('analog', 'analog')], max_length=40)),
                ('value', models.CharField(max_length=120)),
                ('normalized_value', models.CharField(db_index=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='catalog.part')),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='PartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.part')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rub', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(choices=[('in_stock', 'in stock'), ('days_1_3', '1-3 days'), ('preorder', 'preorder'), ('check', 'check')], default='check', max_length=40)),
                ('delivery', models.CharField(blank=True, max_length=160)),
                ('stock', models.CharField(blank=True, max_length=160)),
                ('is_primary', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_offers', to='catalog.part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_offers', to='catalog.supplier')),
            ],
            options={
                'ordering': ['part', '-is_primary', 'price_rub'],
            },
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='unique_car_model_slug_per_brand'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand', 'category'], name='catalog_par_brand_i_6b2b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['condition'], name='catalog_par_conditi_ec88bb_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active'], name='catalog_par_is_acti_ed1084_idx'),
        ),
        migrations.AddIndex(
            model_name='priceoffer',
            index=models.Index(fields=['part', 'is_primary'], name='catalog_pri_part_id_af409b_idx'),
        ),
    ]
