# Generated by Django 5.2.16 on 2026-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('новая', 'новая'), ('контрактная', 'контрактная'), ('восстановленная', 'восстановленная')], default='новая', max_length=40),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='availability',
            field=models.CharField(choices=[('в наличии', 'в наличии'), ('1-3 дня', '1-3 дня'), ('под заказ', 'под заказ'), ('уточнить', 'уточнить')], default='уточнить', max_length=40),
        ),
    ]
