# Generated by Django 5.2.16 on 2026-08-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_part_legacy_id_alter_part_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='fiscal_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='part',
            name='payment_method',
            field=models.CharField(default='full_payment', max_length=80),
        ),
        migrations.AddField(
            model_name='part',
            name='payment_subject',
            field=models.CharField(default='commodity', max_length=80),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.CharField(default='шт.', max_length=40),
        ),
        migrations.AddField(
            model_name='part',
            name='vat_label',
            field=models.CharField(default='НДС не задан', max_length=80),
        ),
    ]
