# Generated by Django 5.2.16 on 2026-08-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_part_fiscal_name_part_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='marking_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='part',
            name='marking_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='marking_status',
            field=models.CharField(choices=[('not_required', 'не требуется'), ('requires_review', 'нужна проверка'), ('confirmed', 'процесс подтвержден'), ('blocked', 'продажа заблокирована')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='photo_kind',
            field=models.CharField(choices=[('illustrative', 'иллюстративное'), ('actual', 'реальное фото товара')], default='illustrative', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='return_terms',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='part',
            name='warranty_terms',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('новая', 'новая'), ('контрактная', 'контрактная'), ('восстановленная', 'восстановленная'), ('б/у', 'б/у')], default='новая', max_length=40),
        ),
        migrations.CreateModel(
            name='PartDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('certificate', 'сертификат'), ('declaration', 'декларация'), ('warranty', 'гарантийный документ'), ('instruction', 'инструкция')], max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to='part-documents/%Y/%m/')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.part')),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
    ]
