# Generated by Django 5.2.16 on 2026-08-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('in_work', 'in work'), ('waiting_customer', 'waiting customer'), ('done', 'done'), ('cancelled', 'cancelled')], default='new', max_length=40)),
                ('source', models.CharField(choices=[('cart', 'cart'), ('request_form', 'request form')], max_length=40)),
                ('customer_name', models.CharField(max_length=160)),
                ('contact', models.CharField(max_length=160)),
                ('vehicle', models.CharField(blank=True, max_length=240)),
                ('request_text', models.TextField(blank=True)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('total_estimate_rub', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.customerrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=240)),
                ('article', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_snapshot_rub', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='catalog.part')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leads.customerrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['status', 'created_at'], name='leads_custo_status_7bef93_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequestevent',
            index=models.Index(fields=['request', 'created_at'], name='leads_custo_request_1d9f9c_idx'),
        ),
    ]
