# Generated by Django 5.2.16 on 2026-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='consent_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='consent_user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='privacy_consent_version',
            field=models.CharField(default='draft-2026-08-15', max_length=80),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='privacy_policy_version',
            field=models.CharField(default='draft-2026-08-15', max_length=80),
        ),
    ]
