# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_customerrequest_consent_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'ordering': ['-created_at'], 'permissions': [('view_request_pii', 'Can view personal data in requests'), ('export_request_pii', 'Can export personal data from requests'), ('anonymize_request_pii', 'Can anonymize personal data in requests')]},
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
