# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at'], 'permissions': [('view_customer_pii', 'Can view customer personal data')]},
        ),
    ]
