# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'permissions': [('view_payment_details', 'Can view payment provider details')]},
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('partially_refunded', 'partially refunded'), ('refunded', 'refunded')], default='draft', max_length=40),
        ),
    ]
