# Generated by Django 5.2.16 on 2026-08-20 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_fiscal_name_orderitem_payment_method_and_more'),
        ('payments', '0002_alter_payment_options_payment_provider_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('in_review', 'in review'), ('waiting_customer', 'waiting customer'), ('approved', 'approved'), ('rejected', 'rejected'), ('resolved', 'resolved')], default='new', max_length=30)),
                ('claim_type', models.CharField(default='quality', max_length=80)),
                ('customer_name', models.CharField(max_length=160)),
                ('contact', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_claim_pii', 'Can view personal data in claims')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='requested', max_length=30)),
                ('amount_rub', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=240)),
                ('manager_comment', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('requested_by', models.CharField(blank=True, max_length=160)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('process_refund', 'Can process payment refunds')],
            },
        ),
        migrations.CreateModel(
            name='RefundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='refunds.refund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_rub', models.PositiveIntegerField(default=0)),
                ('condition_note', models.CharField(blank=True, max_length=240)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='orders.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refunds.refund')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refunds_ref_payment_fa009d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'status'], name='refunds_ref_order_i_47f781_idx'),
        ),
    ]
